=== Qdesnitsa/TMS/src/by/teachmeskills/lesson16_xml_json/xml_xsd/Books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.teachmeskills.by/books1"
  xmlns:b="http://www.teachmeskills.by/books1">

  <element name="books">
    <complexType>
      <sequence>
        <element name="book" type="b:Book" minOccurs="1" maxOccurs="unbounded" />
      </sequence>
    </complexType>
  </element>
  
  <complexType name="Book">
    <sequence>
      <element name="title" type="string" />
      <element name="year" type="integer" />
      <element name="genre" type="string" />
      <element name="author" type="b:Author" />
    </sequence>

    <attribute name="id" type="b:ID" use="required" />

    <attribute name="language" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="English"></enumeration>
          <enumeration value="Russian"></enumeration>
          <enumeration value="German"></enumeration>
        </restriction>
      </simpleType>
    </attribute>
  </complexType>

  <simpleType name="ID">
    <restriction base="integer">
      <pattern value="[0-9]+" />
    </restriction>
  </simpleType>

  <complexType name="Author">
    <sequence>
      <element name="name" type="string" />
      <element name="year" type="integer" />
      <element name="place" type="string" />
    </sequence>
  </complexType>
</schema>

=== Qdesnitsa/TMS/src/by/teachmeskills/lesson16_xml_json/sax/resources/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<b:books xmlns:b="http://www.teachmeskills.by/books"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.teachmeskills.by/books books.xsd">
<book id="01">
  <title>The Little Prince</title>
  <year>1943</year>
  <genre>Novella</genre>
  <author>Antoine de Saint-Exupery</author>
</book>
<book id="02">
  <title>A Tale of Two Cities</title>
  <year>1859</year>
  <genre>Historical fiction</genre>
  <author>Charles Dickens</author>
</book>
<book id="03">
    <title>Harry Potter and the Philosopher's Stone</title>
    <year>1997</year>
    <genre>Fantasy</genre>
    <author>J. K. Rowling</author>
</book>
  <book id="04">
    <title>And Then There Were None</title>
    <year>1939</year>
    <genre>Mystery</genre>
    <author>Agatha Christie</author>
  </book>
  <book id="05">
    <title>Dream of the Red Chamber</title>
    <year>1791</year>
    <genre>Family saga</genre>
    <author>Cao Xueqin</author>
  </book>
</b:books>

=== Qdesnitsa/TMS/src/by/teachmeskills/lesson16_xml_json/xml_xsd/Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<b:books xmlns:b="http://www.teachmeskills.by/books"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.teachmeskills.by/books books.xsd">
<book id="01">
  <title>The Little Prince</title>
  <year>1943</year>
  <genre>Novella</genre>
  <author>
    <name>Antoine de Saint-Exupery</name>
    <year>1900</year>
    <place>France</place>
  </author>
</book>
<book id="02">
  <title>A Tale of Two Cities</title>
  <year>1859</year>
  <genre>Historical fiction</genre>
  <author>
    <name>Charles Dickens</name>
    <year>1812</year>
    <place>England</place>
  </author>
</book>
<book id="03">
    <title>Harry Potter and the Philosopher's Stone</title>
    <year>1997</year>
    <genre>Fantasy</genre>
    <author>
      <name>J. K. Rowling</name>
      <year>1965</year>
      <place>England</place>
    </author>
</book>
</b:books>

=== Qdesnitsa/TMS/lesson/src/by/teachmeskills/lesson18_xml_json/xml_xsd_xslt/Books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<?xml-stylesheet type="text/css" href="Books.css" ?>-->
<?xml-stylesheet type="text/xsl" href="Books.xsl"?>
<b:books xmlns:b="http://www.teachmeskills.by/books1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.teachmeskills.by/books1 Books.xsd">
<book id="01">
  <title>The Little Prince</title>
  <year>1943</year>
  <genre>Novella</genre>
  <author>
    <name>Antoine de Saint-Exupery</name>
    <year>1900</year>
    <place>France</place>
  </author>
  <price>500</price>
</book>
<book id="02">
  <title>A Tale of Two Cities</title>
  <year>1859</year>
  <genre>Historical fiction</genre>
  <author>
    <name>Charles Dickens</name>
    <year>1812</year>
    <place>England</place>
  </author>
  <price>420</price>
</book>
<book id="03">
    <title>Harry Potter and the Philosopher's Stone</title>
    <year>1997</year>
    <genre>Fantasy</genre>
    <author>
      <name>J. K. Rowling</name>
      <year>1965</year>
      <place>England</place>
    </author>
  <price>150</price>
</book>
  <book id="04">
    <title>And Then There Were None</title>
    <year>1939</year>
    <genre>Mystery</genre>
    <author>
      <name>Agatha Christie</name>
      <year>1890</year>
      <place>England</place>
    </author>
    <price>250</price>
  </book>
  <book id="05">
    <title>Dream of the Red Chamber</title>
    <year>1791</year>
    <genre>Family saga</genre>
    <author>
      <name>Cao Xueqin</name>
      <year>1710</year>
      <place>China</place>
    </author>
    <price>100</price>
  </book>
</b:books>
